// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1HDLk0Ejbn72y87esx8wXS9nwbCXs0Cw',
    appId: '1:945849560057:web:2df1fc7683168815c9ab28',
    messagingSenderId: '945849560057',
    projectId: 'lush-layers-aace9',
    authDomain: 'lush-layers-aace9.firebaseapp.com',
    storageBucket: 'lush-layers-aace9.appspot.com',
    measurementId: 'G-0HVN489ZPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjpq3WgSLR5BETxTWA1RcgyW6kYWp75Fs',
    appId: '1:945849560057:android:55a441240ad44137c9ab28',
    messagingSenderId: '945849560057',
    projectId: 'lush-layers-aace9',
    storageBucket: 'lush-layers-aace9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3sRnxc9kfWRFmtwQI_N642QadlPG087Y',
    appId: '1:945849560057:ios:6af1a47e9fc3755ac9ab28',
    messagingSenderId: '945849560057',
    projectId: 'lush-layers-aace9',
    storageBucket: 'lush-layers-aace9.appspot.com',
    androidClientId: '945849560057-jdhhc11jpvjfp2t3q5oc3lnug038tr37.apps.googleusercontent.com',
    iosClientId: '945849560057-jgsu546bm6hjgmfu0h72ftik4nss1tdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3sRnxc9kfWRFmtwQI_N642QadlPG087Y',
    appId: '1:945849560057:ios:6af1a47e9fc3755ac9ab28',
    messagingSenderId: '945849560057',
    projectId: 'lush-layers-aace9',
    storageBucket: 'lush-layers-aace9.appspot.com',
    androidClientId: '945849560057-jdhhc11jpvjfp2t3q5oc3lnug038tr37.apps.googleusercontent.com',
    iosClientId: '945849560057-jgsu546bm6hjgmfu0h72ftik4nss1tdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaperApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1HDLk0Ejbn72y87esx8wXS9nwbCXs0Cw',
    appId: '1:945849560057:web:b6bcecae15c2b1f9c9ab28',
    messagingSenderId: '945849560057',
    projectId: 'lush-layers-aace9',
    authDomain: 'lush-layers-aace9.firebaseapp.com',
    storageBucket: 'lush-layers-aace9.appspot.com',
    measurementId: 'G-FCEMV47QB5',
  );

}